### ISSUE TITLE
There is no module named wiser.rules

### ISSUE THREAD

**Issue by kasuba-badri-vishal** [megagonlabs/tagruler#4]
Traceback (most recent call last):
  File "./api/server.py", line 14, in <module>
    app.add_api("swagger.yml")
  File "/usr/local/lib/python3.7/dist-packages/connexion/apps/flask_app.py", line 54, in add_api
    api = super(FlaskApp, self).add_api(specification, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/connexion/apps/abstract.py", line 155, in add_api
    options=api_options.as_dict())
  File "/usr/local/lib/python3.7/dist-packages/connexion/apis/abstract.py", line 109, in __init__
    self.add_paths()
  File "/usr/local/lib/python3.7/dist-packages/connexion/apis/abstract.py", line 214, in add_paths
    self._handle_add_operation_error(path, method, err.exc_info)
  File "/usr/local/lib/python3.7/dist-packages/connexion/apis/abstract.py", line 228, in _handle_add_operation_error
    six.reraise(*exc_info)
  File "/usr/local/lib/python3.7/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/connexion/resolver.py", line 61, in resolve_function_from_operation_id
    return self.function_resolver(operation_id)
  File "/usr/local/lib/python3.7/dist-packages/connexion/utils.py", line 99, in get_function_from_name
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/content/tagruler/server/api/idea2.py", line 29, in <module>
    from verifier.DB import LF_DB
  File "/content/tagruler/server/verifier/DB.py", line 5, in <module>
    from verifier.translator import make_lf
  File "/content/tagruler/server/verifier/translator.py", line 4, in <module>
    from wiser.rules import TaggingRule # A TaggingRule instance is defined for a tagging LF.
ModuleNotFoundError: No module named 'wiser.rules'

**Comment by kapilpathak1112** [comment]
Hi, I am getting the same error while api/server.py file.

**Comment by kasuba-badri-vishal** [comment]
@Kapil-Pathak 

I was able to solve this error by adding this class definition in "./server/verifier/translator.py" file. Hope this helps

class TaggingRule:
    
    def __init__(self):
        pass

    def apply(self, instances):
        for instance in tqdm(instances):
            # Initializes metadata field
            if self._get_metadata_field() not in instance:
                instance.add_field(self._get_metadata_field(), {})

            # Labels the instance
            labels = self.apply_instance(instance)

            # Stores the labels in the instance
            instance[self._get_metadata_field()][self._get_tr_name()] = labels

    def apply_instance(self, instance):
        raise NotImplementedError

    def _get_metadata_field(self):
        return "WISER_LABELS"

    def _get_tr_name(self):
        return type(self).__name__

**Comment by kapilpathak1112** [comment]
@kasuba-badri-vishal Thanks, it worked

**Comment by kasuba-badri-vishal** [comment]
@Kapil-Pathak 

Hi Kapil, It would be helpful, if you let me know if you are able to use tagruler for custom dataset.

Thanks
